- name: creating the bastion host
  hosts: localhost
  become: true
  connection: local
  gather_facts: false
  tasks:
    - name: importing the bastion_setup variable files
      include_vars: vars/bastion_setup

    - name: importing the variable1 files
      include_vars: vars/vpc-output.var

    - name: creating the ec2_key pair
      ec2_key:
        name: vprofile-key
        region: "{{region}}"
        state: present
      register: keyout

    - name: saving the ec2_key
      copy:
        content: "{{keyout.key.private_key}}"
        dest: "./vprofile-key.pem"
        mode: 0600
      when: keyout.changed

    - name: creating the security group for bastion host
      ec2_group:
        name: bastion-sg
        description: allow port 22 from bastion security group
        region: "{{region}}"
        state: present
        vpc_id: "{{vpcoutid}}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{MYIP}}"
      register: bastionsg_out

    - name: creating the bastion host
      ec2:
        key_name: vprofile-key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{bastion_ami}}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: bastion-host
          project: vprofile
          owner: devopsteam
        exact_count: 1
        count_tag:
          Name: bastion-host
          project: vprofile
          owner: devopsteam
        group_id: "{{bastionsg_out.group_id}}"
        vpc_subnet_id: "{{pubsub1id}}"
      register: bastionhost_out



